"""Step 1: audit the condominium dataset before any modelling decisions.

Produces the evidence that the later cleaning choices are justified by, so
nothing is dropped or imputed on instinct. Writes notes/data-audit.md.
"""
import io
import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

ROOT = Path(__file__).resolve().parent.parent
RAW = Path(
    os.environ.get(
        "CONDO_DATA",
        Path(__file__).resolve().parent.parent / "data" / "condominiums cleaned (1).xlsx",
    )
)
REPORT = ROOT / "notes" / "data-audit.md"

TARGET = "Price USD"
NEAR_CONSTANT_THRESHOLD = 0.90  # a feature at one value in >=90% of rows
SPARSE_THRESHOLD = 0.50  # a feature missing in >=50% of rows

log: list[str] = []


def note(msg: str = "") -> None:
    print(msg)
    log.append(msg)


def main() -> None:
    df = pd.read_excel(RAW)
    note(f"# Data audit — condominium dataset\n")
    note(f"Generated by `src/audit_data.py`.\n")
    note(f"**{len(df)} rows x {df.shape[1]} columns**\n")

    # --- Target ------------------------------------------------------------
    note("## 1. Target: `Price USD`\n")
    have = df[TARGET].notna()
    note(f"- Present: **{have.sum()}** | missing: **{(~have).sum()}**")
    note(f"- Trainable rows: **{have.sum()}** — the target cannot be imputed "
         "without the model learning the imputation rule instead of the market.")
    note(f"- Rows missing the target cluster by neighbourhood: "
         f"{df.loc[~have,'Neighborhood'].value_counts().head(3).to_dict()}")
    d = df[have].copy()
    note()
    note("Distribution (USD):\n")
    note("```")
    note(d[TARGET].describe().round(0).to_string())
    note("```")
    skew = d[TARGET].skew()
    note(f"\n- Skew: **{skew:.2f}** -> "
         f"{'log transform justified' if abs(skew) > 0.5 else 'roughly symmetric'}")
    note(f"- Skew after log: **{np.log(d[TARGET]).skew():.2f}**\n")

    # --- Missingness -------------------------------------------------------
    note("## 2. Missingness among predictors\n")
    miss = d.drop(columns=[TARGET]).isna().mean().sort_values(ascending=False)
    note("| Feature | Missing % | Verdict |")
    note("|---|---|---|")
    for col, frac in miss.items():
        if frac >= SPARSE_THRESHOLD:
            verdict = "**too sparse to impute** — imputing would invent the variable"
        elif frac > 0:
            verdict = "impute inside CV, add indicator"
        else:
            verdict = "complete"
        note(f"| `{col}` | {frac*100:.1f}% | {verdict} |")
    note()

    # --- Near-constant features -------------------------------------------
    note("## 3. Near-constant features\n")
    note("A predictor that barely varies cannot explain variation in price; it "
         "only adds noise and dilutes tree splits.\n")
    note("| Feature | Modal value | Share at mode | Verdict |")
    note("|---|---|---|---|")
    drop_constant = []
    for col in d.columns:
        if col == TARGET or d[col].dtype == object:
            continue
        # Exclude NaN so "near-constant" measures variation among observed
        # values; sparsity is judged separately in section 2.
        vc = d[col].value_counts(normalize=True, dropna=True)
        if vc.empty:
            continue
        share = vc.iloc[0]
        if share >= NEAR_CONSTANT_THRESHOLD:
            drop_constant.append(col)
            verdict = "**drop** — near-constant"
        else:
            verdict = "keep"
        note(f"| `{col}` | {vc.index[0]} | {share*100:.1f}% | {verdict} |")
    note()

    # --- Location granularity ---------------------------------------------
    note("## 4. Location granularity\n")
    pairs = d.groupby(["Latitude", "Longitude"]).ngroups
    note(f"- Unique latitudes: **{d.Latitude.nunique()}**, "
         f"longitudes: **{d.Longitude.nunique()}**, "
         f"lat/long pairs: **{pairs}**")
    note(f"- Neighbourhood values: **{d.Neighborhood.nunique()}**")
    note(f"- Average rows per coordinate pair: **{len(d)/pairs:.1f}**\n")
    note("Coordinates are neighbourhood centroids, not property locations. They "
         "duplicate `Neighborhood`, so including both risks multicollinearity — "
         "checked with VIF in the diagnostics step.\n")

    # --- Signal check ------------------------------------------------------
    note("## 5. Univariate signal against log(price)\n")
    d["log_price"] = np.log(d[TARGET])
    note("| Feature | n (complete pairs) | Pearson r |")
    note("|---|---|---|")
    for col in d.columns:
        if col in (TARGET, "log_price") or d[col].dtype == object:
            continue
        sub = d[[col, "log_price"]].dropna()
        r = sub[col].corr(sub["log_price"]) if len(sub) > 2 else np.nan
        note(f"| `{col}` | {len(sub)} | {r:+.3f} |")
    note()

    # --- Conclusions -------------------------------------------------------
    sparse = [c for c, f in miss.items() if f >= SPARSE_THRESHOLD]
    note("## Decisions this audit supports\n")
    note(f"1. Train on the **{have.sum()}** rows with a real price; keep the "
         f"{(~have).sum()} priceless rows aside as a demo prediction set.")
    note(f"2. Drop as too sparse: {', '.join(f'`{c}`' for c in sparse) or 'none'}.")
    note(f"3. Drop as near-constant: {', '.join(f'`{c}`' for c in drop_constant) or 'none'}.")
    note("4. Log-transform the target.")
    note("5. Impute what remains **inside** the CV pipeline, never before splitting.")
    note("6. Check `Latitude`/`Longitude` against `Neighborhood` for "
         "multicollinearity before keeping both.")

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(log) + "\n", encoding="utf-8")
    print(f"\nWrote -> notes/{REPORT.name}")


if __name__ == "__main__":
    main()
