"""Step 4: hedonic regression diagnostics.

Runs the standard checks on the OLS hedonic specification before any model
selection: multicollinearity (VIF), heteroskedasticity (Breusch-Pagan),
residual normality (Jarque-Bera, Q-Q), functional form (RESET), and
influential observations (Cook's distance).

Spatial diagnostics (Moran's I, LISA) are deliberately absent: the data has no
property coordinates, only 16 neighbourhood centroids across 87 rows, which is
far too coarse to support spatial autocorrelation inference.

Writes notes/diagnostics-report.md and results/diagnostics_*.png.
"""
import io
import os
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import statsmodels.api as sm
from statsmodels.stats.diagnostic import het_breuschpagan, linear_reset
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.stats.stattools import jarque_bera

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

ROOT = Path(__file__).resolve().parent.parent
RAW = Path(
    os.environ.get(
        "CONDO_DATA",
        Path(__file__).resolve().parent.parent / "data" / "condominiums cleaned (1).xlsx",
    )
)
REPORT = ROOT / "notes" / "diagnostics-report.md"
FIGDIR = ROOT / "results"

# Established by the audit (src/audit_data.py).
DROP_NEAR_CONSTANT = [
    "Essential_Utilities_score",
    "Premium_features_score",
    "Wellness_score",
]
DROP_TOO_SPARSE = ["final size"]  # 10 observations out of 87

log: list[str] = []


def note(msg: str = "") -> None:
    print(msg)
    log.append(msg)


def prepare() -> pd.DataFrame:
    df = pd.read_excel(RAW)
    d = df[df["Price USD"].notna()].copy()
    d["log_price"] = np.log(d["Price USD"])

    # Median-fill only for the diagnostic fit; the modelling pipeline imputes
    # inside CV. Diagnostics need one complete matrix to test a specification.
    for col in ["Bedrooms", "Bathrooms"]:
        d[col + "_observed"] = d[col].notna().astype(int)
        d[col] = d[col].fillna(d[col].median())

    d = d.drop(columns=DROP_NEAR_CONSTANT + DROP_TOO_SPARSE)
    return d


def vif_table(X: pd.DataFrame) -> pd.DataFrame:
    Xc = sm.add_constant(X)
    return pd.DataFrame(
        {
            "feature": X.columns,
            "VIF": [
                variance_inflation_factor(Xc.values, i + 1) for i in range(X.shape[1])
            ],
        }
    ).sort_values("VIF", ascending=False)


def report_vif(X: pd.DataFrame, label: str) -> pd.DataFrame:
    note(f"\n**{label}**\n")
    v = vif_table(X)
    note("| Feature | VIF | |")
    note("|---|---|---|")
    for _, r in v.iterrows():
        flag = "**severe (>10)**" if r.VIF > 10 else ("elevated (>5)" if r.VIF > 5 else "ok")
        note(f"| `{r.feature}` | {r.VIF:.2f} | {flag} |")
    return v


def main() -> None:
    FIGDIR.mkdir(parents=True, exist_ok=True)
    d = prepare()
    y = d["log_price"]

    note("# Hedonic diagnostics\n")
    note("Generated by `src/diagnostics.py`.\n")
    note(f"Specification fitted on **{len(d)} rows**, target `log(Price USD)`.\n")
    note("Dropped before fitting, per the data audit: "
         + ", ".join(f"`{c}`" for c in DROP_NEAR_CONSTANT + DROP_TOO_SPARSE) + ".\n")

    # --- Multicollinearity -------------------------------------------------
    note("## 1. Multicollinearity (VIF)\n")
    note("VIF above 10 indicates a variable is largely explained by the others, "
         "making its coefficient unstable and its sign untrustworthy.")

    full = ["Bedrooms", "Bathrooms", "Latitude", "Longitude",
            "Security_score", "Access_score", "View_and _outdoor_score"]
    report_vif(d[full], "All numeric predictors, coordinates included")

    note("\nCoordinates are neighbourhood centroids, so they encode the same "
         "information as `Neighborhood`. Re-checking without them:")
    no_coord = [c for c in full if c not in ("Latitude", "Longitude")]
    report_vif(d[no_coord], "Coordinates removed")

    # --- OLS fit -----------------------------------------------------------
    note("\n## 2. OLS hedonic fit\n")
    X = sm.add_constant(d[full])
    model = sm.OLS(y, X).fit()
    note("```")
    note(str(model.summary()))
    note("```")

    resid, fitted = model.resid, model.fittedvalues

    # --- Heteroskedasticity ------------------------------------------------
    note("\n## 3. Heteroskedasticity (Breusch-Pagan)\n")
    lm, lm_p, f, f_p = het_breuschpagan(resid, X)
    note(f"- LM statistic **{lm:.3f}**, p = **{lm_p:.4f}**")
    note(f"- {'Heteroskedasticity detected' if lm_p < 0.05 else 'No evidence of heteroskedasticity'} "
         f"at the 5% level.")
    if lm_p < 0.05:
        note("- Use heteroskedasticity-robust (HC3) standard errors for inference.")

    # --- Normality ---------------------------------------------------------
    note("\n## 4. Residual normality (Jarque-Bera)\n")
    jb, jb_p, skew, kurt = jarque_bera(resid)
    note(f"- JB **{jb:.3f}**, p = **{jb_p:.4f}**, skew {skew:.3f}, kurtosis {kurt:.3f}")
    note(f"- {'Residuals depart from normality' if jb_p < 0.05 else 'Residuals consistent with normality'} "
         "at the 5% level.")

    # --- Functional form ---------------------------------------------------
    note("\n## 5. Functional form (Ramsey RESET)\n")
    try:
        reset = linear_reset(model, power=2, use_f=True)
        note(f"- F = **{reset.fvalue:.3f}**, p = **{reset.pvalue:.4f}**")
        note(f"- {'Misspecification suggested — consider non-linear terms' if reset.pvalue < 0.05 else 'No evidence of functional-form misspecification'}.")
    except Exception as exc:
        note(f"- RESET could not be computed: {type(exc).__name__}")

    # --- Influence ---------------------------------------------------------
    note("\n## 6. Influential observations (Cook's distance)\n")
    cooks = model.get_influence().cooks_distance[0]
    threshold = 4 / len(d)
    flagged = int((cooks > threshold).sum())
    note(f"- Threshold 4/n = **{threshold:.4f}**")
    note(f"- **{flagged}** observations exceed it ({flagged/len(d)*100:.1f}% of the sample)")
    note(f"- Largest Cook's distance: **{cooks.max():.3f}**")

    # --- Figures -----------------------------------------------------------
    fig, ax = plt.subplots(1, 3, figsize=(15, 4.2))
    sm.qqplot(resid, line="s", ax=ax[0])
    ax[0].set_title("Q-Q plot of residuals")
    ax[1].scatter(fitted, resid, alpha=0.7, edgecolor="k", linewidth=0.4)
    ax[1].axhline(0, color="crimson", lw=1)
    ax[1].set(xlabel="Fitted", ylabel="Residual", title="Residuals vs fitted")
    ax[2].stem(np.arange(len(cooks)), cooks, markerfmt=",")
    ax[2].axhline(threshold, color="crimson", ls="--", lw=1, label=f"4/n = {threshold:.3f}")
    ax[2].set(xlabel="Observation", ylabel="Cook's distance", title="Influence")
    ax[2].legend()
    fig.tight_layout()
    fig.savefig(FIGDIR / "diagnostics_ols.png", dpi=130)
    note(f"\nFigures -> `results/diagnostics_ols.png`")

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(log) + "\n", encoding="utf-8")
    print(f"Wrote -> notes/{REPORT.name}")


if __name__ == "__main__":
    main()
